# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'card.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Card(object):
    def setupUi(self, card):
        card.setObjectName("card")
        card.resize(741, 586)
        self.cardwidget = QtWidgets.QWidget(card)
        self.cardwidget.setStyleSheet("border: 10px solid #00FFFF;\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.cardwidget.setObjectName("cardwidget")
        self.SettingsButton = QtWidgets.QPushButton(self.cardwidget)
        self.SettingsButton.setGeometry(QtCore.QRect(660, 510, 81, 71))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(20)
        self.SettingsButton.setFont(font)
        self.SettingsButton.setObjectName("SettingsButton")
        self.cardtext = QtWidgets.QTextEdit(self.cardwidget)
        self.cardtext.setGeometry(QtCore.QRect(0, 0, 741, 581))
        self.cardtext.setObjectName("cardtext")
        self.nextButton = QtWidgets.QPushButton(self.cardwidget)
        self.nextButton.setGeometry(QtCore.QRect(0, 510, 661, 61))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(20)
        self.nextButton.setFont(font)
        self.nextButton.setStyleSheet("border-bottom-color: rgb(255, 255, 255);")
        self.nextButton.setObjectName("nextButton")
        self.cardtext.raise_()
        self.SettingsButton.raise_()
        self.nextButton.raise_()
        card.setCentralWidget(self.cardwidget)

        self.retranslateUi(card)
        QtCore.QMetaObject.connectSlotsByName(card)

    def retranslateUi(self, card):
        _translate = QtCore.QCoreApplication.translate
        card.setWindowTitle(_translate("card", "MainWindow"))
        self.SettingsButton.setText(_translate("card", "#"))
        self.nextButton.setText(_translate("card", "Продолжить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    card = QtWidgets.QMainWindow()
    ui = Ui_Card()
    ui.setupUi(card)
    card.show()
    sys.exit(app.exec_())
