# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'maksonpage.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow5(object):
    def setupUi(self, MainWindow5):
        MainWindow5.setObjectName("MainWindow5")
        MainWindow5.resize(1643, 797)
        font = QtGui.QFont()
        font.setPointSize(12)
        MainWindow5.setFont(font)
        MainWindow5.setMouseTracking(True)
        MainWindow5.setTabletTracking(True)
        MainWindow5.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        MainWindow5.setAnimated(True)
        self.centralwidget5 = QtWidgets.QWidget(MainWindow5)
        self.centralwidget5.setObjectName("centralwidget5")
        self.listWidget = QtWidgets.QTabWidget(self.centralwidget5)
        self.listWidget.setGeometry(QtCore.QRect(-10, 40, 1661, 761))
        self.listWidget.setObjectName("listWidget")
        self.list1 = QtWidgets.QWidget()
        self.list1.setObjectName("list1")
        self.blue_block_up = QtWidgets.QLabel(self.list1)
        self.blue_block_up.setGeometry(QtCore.QRect(10, 0, 1641, 161))
        self.blue_block_up.setStyleSheet("background-color: #34fafa;\n"
"border: 1px solid #000000;\n"
"border-bottom-color: rgb(0, 0, 0);\n"
"border-right-color: rgb(0, 0, 0);")
        self.blue_block_up.setText("")
        self.blue_block_up.setObjectName("blue_block_up")
        self.minus_list_Button = QtWidgets.QPushButton(self.list1)
        self.minus_list_Button.setGeometry(QtCore.QRect(380, 0, 171, 161))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.minus_list_Button.setFont(font)
        self.minus_list_Button.setStyleSheet("border:2px solid #000000;\n"
"background-color: rgb(217, 0, 217);")
        self.minus_list_Button.setObjectName("minus_list_Button")
        self.plus_list_Button = QtWidgets.QPushButton(self.list1)
        self.plus_list_Button.setGeometry(QtCore.QRect(210, 0, 171, 161))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.plus_list_Button.setFont(font)
        self.plus_list_Button.setStyleSheet("border:2px solid #000000;\n"
"background-color: rgb(217, 0, 217);")
        self.plus_list_Button.setObjectName("plus_list_Button")
        self.icon = QtWidgets.QLabel(self.list1)
        self.icon.setGeometry(QtCore.QRect(10, 10, 181, 141))
        self.icon.setAutoFillBackground(False)
        self.icon.setStyleSheet("background-color: rgb(0, 255, 255);\n"
"")
        self.icon.setText("")
        self.icon.setPixmap(QtGui.QPixmap("project3/pycache/catcat.png"))
        self.icon.setObjectName("icon")
        self.purpleblock1 = QtWidgets.QLabel(self.list1)
        self.purpleblock1.setGeometry(QtCore.QRect(1510, 160, 41, 621))
        self.purpleblock1.setStyleSheet("background-color: rgb(237, 0, 237);\n"
"border: 1px solid #000000;")
        self.purpleblock1.setText("")
        self.purpleblock1.setObjectName("purpleblock1")
        self.purpleblock2 = QtWidgets.QLabel(self.list1)
        self.purpleblock2.setGeometry(QtCore.QRect(1580, 160, 41, 621))
        self.purpleblock2.setStyleSheet("background-color: rgb(237, 0, 237);\n"
"border: 1px solid #000000;")
        self.purpleblock2.setText("")
        self.purpleblock2.setObjectName("purpleblock2")
        self.plus_table_Button = QtWidgets.QPushButton(self.list1)
        self.plus_table_Button.setGeometry(QtCore.QRect(10, 280, 171, 161))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.plus_table_Button.setFont(font)
        self.plus_table_Button.setStyleSheet("border:2px solid #000000;\n"
"background-color: rgb(0, 255, 255);")
        self.plus_table_Button.setObjectName("plus_table_Button")
        # self.minus_table_Button = QtWidgets.QPushButton(self.list1)
        # self.minus_table_Button.se

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    card = QtWidgets.QMainWindow()
    ui = Ui_MainWindow5()
    ui.setupUi(card)
    card.show()
    sys.exit(app.exec_())