# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'maksoncard.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1015, 758)
        self.Table = QtWidgets.QWidget(Form)
        self.Table.setGeometry(QtCore.QRect(30, 100, 371, 591))
        self.Table.setStyleSheet("border:2px solid #000000;\n"
"background-color: rgb(0, 255, 255);")
        self.Table.setObjectName("Table")
        self.plus_card_Button = QtWidgets.QPushButton(self.Table)
        self.plus_card_Button.setGeometry(QtCore.QRect(0, 160, 171, 81))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.plus_card_Button.setFont(font)
        self.plus_card_Button.setStyleSheet("border:2px solid #000000;\n"
"background-color: rgb(255, 255, 255);")
        self.plus_card_Button.setObjectName("plus_card_Button")
        self.minus_card_Button = QtWidgets.QPushButton(self.Table)
        self.minus_card_Button.setGeometry(QtCore.QRect(170, 160, 201, 81))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.minus_card_Button.setFont(font)
        self.minus_card_Button.setStyleSheet("border:2px solid #000000;\n"
"background-color: rgb(255, 255, 255);")
        self.minus_card_Button.setObjectName("minus_card_Button")
        self.Card = QtWidgets.QWidget(self.Table)
        self.Card.setGeometry(QtCore.QRect(0, 0, 371, 161))
        self.Card.setObjectName("Card")
        self.text_card = QtWidgets.QPlainTextEdit(self.Card)
        self.text_card.setGeometry(QtCore.QRect(10, 10, 351, 141))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(20)
        self.text_card.setFont(font)
        self.text_card.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.text_card.setObjectName("text_card")
        self.card_option = QtWidgets.QPushButton(self.Card)
        self.card_option.setGeometry(QtCore.QRect(330, 120, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.card_option.setFont(font)
        self.card_option.setStyleSheet("background-color: rgb(255, 0, 255);")
        self.card_option.setObjectName("card_option")
        self.card_label1 = QtWidgets.QLabel(self.Table)
        self.card_label1.setGeometry(QtCore.QRect(20, 170, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(8)
        self.card_label1.setFont(font)
        self.card_label1.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(255, 255, 255);")
        self.card_label1.setObjectName("card_label1")
        self.card_label2 = QtWidgets.QLabel(self.Table)
        self.card_label2.setGeometry(QtCore.QRect(210, 170, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(8)
        self.card_label2.setFont(font)
        self.card_label2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(255, 255, 255);")
        self.card_label2.setObjectName("card_label2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.plus_card_Button.setText(_translate("Form", "+"))
        self.minus_card_Button.setText(_translate("Form", "-"))
        self.text_card.setPlainText(_translate("Form", "название карточки"))
        self.card_option.setText(_translate("Form", "?"))
        self.card_label1.setText(_translate("Form", "Добавить карточку"))
        self.card_label2.setText(_translate("Form", "Удалить карточку"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
