# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'maksonpage.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow5(object):
    def setupUi(self, MainWindow5):
        MainWindow5.setObjectName("MainWindow5")
        MainWindow5.resize(1643, 797)
        font = QtGui.QFont()
        font.setPointSize(12)
        MainWindow5.setFont(font)
        MainWindow5.setMouseTracking(True)
        MainWindow5.setTabletTracking(True)
        MainWindow5.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        MainWindow5.setAnimated(True)
        self.centralwidget5 = QtWidgets.QWidget(MainWindow5)
        self.centralwidget5.setObjectName("centralwidget5")
        self.listWidget = QtWidgets.QTabWidget(self.centralwidget5)
        self.listWidget.setGeometry(QtCore.QRect(-10, 40, 1661, 761))
        self.listWidget.setObjectName("listWidget")
        self.list1 = QtWidgets.QWidget()
        self.list1.setObjectName("list1")
        self.blue_block_up = QtWidgets.QLabel(self.list1)
        self.blue_block_up.setGeometry(QtCore.QRect(10, 0, 1641, 161))
        self.blue_block_up.setStyleSheet("background-color: #34fafa;\n"
"border: 1px solid #000000;\n"
"border-bottom-color: rgb(0, 0, 0);\n"
"border-right-color: rgb(0, 0, 0);")
        self.blue_block_up.setText("")
        self.blue_block_up.setObjectName("blue_block_up")
        self.minus_list_Button = QtWidgets.QPushButton(self.list1)
        self.minus_list_Button.setGeometry(QtCore.QRect(380, 0, 171, 161))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.minus_list_Button.setFont(font)
        self.minus_list_Button.setStyleSheet("border:2px solid #000000;\n"
"background-color: rgb(217, 0, 217);")
        self.minus_list_Button.setObjectName("minus_list_Button")
        self.plus_list_Button = QtWidgets.QPushButton(self.list1)
        self.plus_list_Button.setGeometry(QtCore.QRect(210, 0, 171, 161))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.plus_list_Button.setFont(font)
        self.plus_list_Button.setStyleSheet("border:2px solid #000000;\n"
"background-color: rgb(217, 0, 217);")
        self.plus_list_Button.setObjectName("plus_list_Button")
        self.icon = QtWidgets.QLabel(self.list1)
        self.icon.setGeometry(QtCore.QRect(10, 10, 181, 141))
        self.icon.setAutoFillBackground(False)
        self.icon.setStyleSheet("background-color: rgb(0, 255, 255);\n"
"")
        self.icon.setText("")
        self.icon.setPixmap(QtGui.QPixmap("project3/__pycache__/catcat.png"))
        self.icon.setObjectName("icon")
        self.purpleblock1 = QtWidgets.QLabel(self.list1)
        self.purpleblock1.setGeometry(QtCore.QRect(1510, 160, 41, 621))
        self.purpleblock1.setStyleSheet("background-color: rgb(237, 0, 237);\n"
"border: 1px solid #000000;")
        self.purpleblock1.setText("")
        self.purpleblock1.setObjectName("purpleblock1")
        self.purpleblock2 = QtWidgets.QLabel(self.list1)
        self.purpleblock2.setGeometry(QtCore.QRect(1580, 160, 41, 621))
        self.purpleblock2.setStyleSheet("background-color: rgb(237, 0, 237);\n"
"border: 1px solid #000000;")
        self.purpleblock2.setText("")
        self.purpleblock2.setObjectName("purpleblock2")
        self.plus_table_Button = QtWidgets.QPushButton(self.list1)
        self.plus_table_Button.setGeometry(QtCore.QRect(10, 280, 171, 161))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.plus_table_Button.setFont(font)
        self.plus_table_Button.setStyleSheet("border:2px solid #000000;\n"
"background-color: rgb(0, 255, 255);")
        self.plus_table_Button.setObjectName("plus_table_Button")
        self.minus_table_Button = QtWidgets.QPushButton(self.list1)
        self.minus_table_Button.setGeometry(QtCore.QRect(10, 440, 171, 161))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.minus_table_Button.setFont(font)
        self.minus_table_Button.setStyleSheet("border:2px solid #000000;\n"
"background-color: rgb(0, 255, 255);")
        self.minus_table_Button.setObjectName("minus_table_Button")
        self.labeltable1 = QtWidgets.QLabel(self.list1)
        self.labeltable1.setGeometry(QtCore.QRect(220, 20, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.labeltable1.setFont(font)
        self.labeltable1.setStyleSheet("background-color: rgb(217, 0, 217);")
        self.labeltable1.setObjectName("labeltable1")
        self.labeltable2 = QtWidgets.QLabel(self.list1)
        self.labeltable2.setGeometry(QtCore.QRect(390, 20, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.labeltable2.setFont(font)
        self.labeltable2.setStyleSheet("background-color: rgb(217, 0, 217);")
        self.labeltable2.setObjectName("labeltable2")
        self.labelblock1 = QtWidgets.QLabel(self.list1)
        self.labelblock1.setGeometry(QtCore.QRect(20, 470, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.labelblock1.setFont(font)
        self.labelblock1.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.labelblock1.setObjectName("labelblock1")
        self.labelblock2 = QtWidgets.QLabel(self.list1)
        self.labelblock2.setGeometry(QtCore.QRect(20, 290, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.labelblock2.setFont(font)
        self.labelblock2.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.labelblock2.setObjectName("labelblock2")
        self.listWidget.addTab(self.list1, "")
        self.myTablesButton = QtWidgets.QPushButton(self.centralwidget5)
        self.myTablesButton.setGeometry(QtCore.QRect(0, 0, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.myTablesButton.setFont(font)
        self.myTablesButton.setObjectName("myTablesButton")
        self.EscapeButton = QtWidgets.QPushButton(self.centralwidget5)
        self.EscapeButton.setGeometry(QtCore.QRect(130, 0, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.EscapeButton.setFont(font)
        self.EscapeButton.setObjectName("EscapeButton")
        MainWindow5.setCentralWidget(self.centralwidget5)

        self.retranslateUi(MainWindow5)
        self.listWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow5)

    def retranslateUi(self, MainWindow5):
        _translate = QtCore.QCoreApplication.translate
        MainWindow5.setWindowTitle(_translate("MainWindow5", "MainWindow"))
        self.minus_list_Button.setText(_translate("MainWindow5", "-"))
        self.plus_list_Button.setText(_translate("MainWindow5", "+"))
        self.plus_table_Button.setText(_translate("MainWindow5", "+"))
        self.minus_table_Button.setText(_translate("MainWindow5", "-"))
        self.labeltable1.setText(_translate("MainWindow5", "Добавить таблицу"))
        self.labeltable2.setText(_translate("MainWindow5", "Удалить таблицу"))
        self.labelblock1.setText(_translate("MainWindow5", "Удалить столбец"))
        self.labelblock2.setText(_translate("MainWindow5", "Добавить столбец"))
        self.listWidget.setTabText(self.listWidget.indexOf(self.list1), _translate("MainWindow5", "Tab 1"))
        self.myTablesButton.setText(_translate("MainWindow5", "Мои таблицы"))
        self.EscapeButton.setText(_translate("MainWindow5", "Выход"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow5 = QtWidgets.QMainWindow()
    ui = Ui_MainWindow5()
    ui.setupUi(MainWindow5)
    MainWindow5.show()
    sys.exit(app.exec_())
