# -*- coding: utf-8 -*-

# Card implementation generated from reading ui file 'page5.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow5):
# Окно
        MainWindow5.setObjectName("MainWindow5")
        MainWindow5.resize(1643, 797)
        font = QtGui.QFont()
        font.setPointSize(12)
        MainWindow5.setFont(font)
        MainWindow5.setMouseTracking(True)
        MainWindow5.setTabletTracking(True)
        MainWindow5.setStyleSheet("background-color: rgb(255, 255, 255);\n" "")
        MainWindow5.setAnimated(True)

# 
        self.centralwidget5 = QtWidgets.QWidget(MainWindow5)
        self.centralwidget5.setObjectName("centralwidget5")
        self.listWidget = QtWidgets.QTabWidget(self.centralwidget5)
        self.listWidget.setGeometry(QtCore.QRect(-10, 40, 1661, 761))
        self.listWidget.setObjectName("listWidget")
        self.list1 = QtWidgets.QWidget()
        self.list1.setObjectName("list1")

# 
        self.blue_block_up = QtWidgets.QLabel(self.list1)
        self.blue_block_up.setGeometry(QtCore.QRect(10, 0, 1641, 161))
        self.blue_block_up.setStyleSheet("background-color: #34fafa;\n""border: 1px solid #000000;\n""border-bottom-color: rgb(0, 0, 0);\n""border-right-color: rgb(0, 0, 0);")
        self.blue_block_up.setText("")
        self.blue_block_up.setObjectName("blue_block_up")

# минус лист
        self.minus_list_Button = QtWidgets.QPushButton(self.list1)
        self.minus_list_Button.setGeometry(QtCore.QRect(380, 0, 171, 161))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.minus_list_Button.setFont(font)
        self.minus_list_Button.setStyleSheet("border:2px solid #000000;\n""background-color: rgb(217, 0, 217);")
        self.minus_list_Button.setObjectName("minus_list_Button")
# плюс лист
        self.plus_list_Button = QtWidgets.QPushButton(self.list1)
        self.plus_list_Button.setGeometry(QtCore.QRect(210, 0, 171, 161))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.plus_list_Button.setFont(font)
        self.plus_list_Button.setStyleSheet("border:2px solid #000000;\n""background-color: rgb(217, 0, 217);")
        self.plus_list_Button.setObjectName("plus_list_Button")
        self.plus_list_Button.clicked.connect(self.add_tab)
# иконка в верхнем левом углу
        self.icon = QtWidgets.QLabel(self.list1)
        self.icon.setGeometry(QtCore.QRect(10, 10, 181, 141))
        self.icon.setAutoFillBackground(False)
        self.icon.setStyleSheet("background-color: rgb(0, 255, 255);\n""")
        self.icon.setText("")
        self.icon.setPixmap(QtGui.QPixmap("catcat.png"))
        self.icon.setObjectName("icon")

# Фиол колонки с права, вроде как больше не нужны
        # self.purpleblock1 = QtWidgets.QLabel(self.list1)
        # self.purpleblock1.setGeometry(QtCore.QRect(1510, 160, 41, 621))
        # self.purpleblock1.setStyleSheet("background-color: rgb(237, 0, 237);\n""border: 1px solid #000000;")
        # self.purpleblock1.setText("")
        # self.purpleblock1.setObjectName("purpleblock1")
        # self.purpleblock2 = QtWidgets.QLabel(self.list1)
        # self.purpleblock2.setGeometry(QtCore.QRect(1580, 160, 41, 621))
        # self.purpleblock2.setStyleSheet("background-color: rgb(237, 0, 237);\n""border: 1px solid #000000;")
        # self.purpleblock2.setText("")
        # self.purpleblock2.setObjectName("purpleblock2")

# Таблица? 
        self.Table = QtWidgets.QWidget(self.list1)
        self.Table.setGeometry(QtCore.QRect(10, 160, 371, 591))
        self.Table.setStyleSheet("border:2px solid #000000;\n" "background-color: rgb(0, 255, 255);")
        self.Table.setObjectName("Table")

# Первая карточка
        self.Card = QtWidgets.QWidget(self.Table)
        self.Card.setGeometry(QtCore.QRect(0, 80, 371, 168))
        self.Card.setObjectName("Card")

# Настройки карточки, отключены до лучших времён
        # self.card_option = QtWidgets.QPushButton(self.Card)
        # self.card_option.setGeometry(QtCore.QRect(340, 130, 31, 31))
        # font = QtGui.QFont()
        # font.setPointSize(12)
        # self.card_option.setFont(font)
        # self.card_option.setObjectName("card_option")

# Добавить карточку
        self.plus_card_Button = QtWidgets.QPushButton(self.Table)
        self.plus_card_Button.setGeometry(QtCore.QRect(0, 0, 171, 81))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.plus_card_Button.setFont(font)
        self.plus_card_Button.setStyleSheet("border:2px solid #000000;\n" "background-color: rgb(255, 255, 255);")
        self.plus_card_Button.setObjectName("plus_card_Button")

# Удалить карточку
        self.minus_card_Button = QtWidgets.QPushButton(self.Table)
        self.minus_card_Button.setGeometry(QtCore.QRect(170, 0, 201, 81))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.minus_card_Button.setFont(font)
        self.minus_card_Button.setStyleSheet("border:2px solid #000000;\n" "background-color: rgb(255, 255, 255);")
        self.minus_card_Button.setObjectName("minus_card_Button")


# Надпись "Добавить карточку"
        self.card_label1 = QtWidgets.QLabel(self.Table)
        self.card_label1.setGeometry(QtCore.QRect(20, 5, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(8)
        self.card_label1.setFont(font)
        self.card_label1.setStyleSheet("background-color: rgb(255, 255, 255);\n""border-color: rgb(255, 255, 255);")
        self.card_label1.setObjectName("card_label1")

# Надпись "Удалить карточку"
        self.card_label2 = QtWidgets.QLabel(self.Table)
        self.card_label2.setGeometry(QtCore.QRect(210, 5, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(8)
        self.card_label2.setFont(font)
        self.card_label2.setStyleSheet("background-color: rgb(255, 255, 255);\n""border-color: rgb(255, 255, 255);")
        self.card_label2.setObjectName("card_label2")

# Добавить таблицу
        self.plus_table_Button = QtWidgets.QPushButton(self.list1)
        self.plus_table_Button.setGeometry(QtCore.QRect(1480, 280, 171, 161))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.plus_table_Button.setFont(font)
        self.plus_table_Button.setStyleSheet("border:2px solid #000000;\n""background-color: rgb(0, 255, 255);")
        self.plus_table_Button.setObjectName("plus_table_Button")

# Удалить таблицу
        self.minus_table_Button = QtWidgets.QPushButton(self.list1)
        self.minus_table_Button.setGeometry(QtCore.QRect(1480, 440, 171, 161))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.minus_table_Button.setFont(font)
        self.minus_table_Button.setStyleSheet("border:2px solid #000000;\n""background-color: rgb(0, 255, 255);")
        self.minus_table_Button.setObjectName("minus_table_Button")

# Надпись "Добавить таблицу"
        self.labeltable1 = QtWidgets.QLabel(self.list1)
        self.labeltable1.setGeometry(QtCore.QRect(220, 20, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.labeltable1.setFont(font)
        self.labeltable1.setStyleSheet("background-color: rgb(217, 0, 217);")
        self.labeltable1.setObjectName("labeltable1")

# Надпись "Удалить таблицу"
        self.labeltable2 = QtWidgets.QLabel(self.list1)
        self.labeltable2.setGeometry(QtCore.QRect(390, 20, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.labeltable2.setFont(font)
        self.labeltable2.setStyleSheet("background-color: rgb(217, 0, 217);")
        self.labeltable2.setObjectName("labeltable2")

# Надпись "Удалить столбец"
        self.labelblock1 = QtWidgets.QLabel(self.list1)
        self.labelblock1.setGeometry(QtCore.QRect(1490, 450, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.labelblock1.setFont(font)
        self.labelblock1.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.labelblock1.setObjectName("labelblock1")

# Надпись "Добавить столбец"
        self.labelblock2 = QtWidgets.QLabel(self.list1)
        self.labelblock2.setGeometry(QtCore.QRect(1490, 290, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.labelblock2.setFont(font)
        self.labelblock2.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.labelblock2.setObjectName("labelblock2")

# Что-то там сверху
        self.listWidget.addTab(self.list1, "")
        self.myTablesButton = QtWidgets.QPushButton(self.centralwidget5)
        self.myTablesButton.setGeometry(QtCore.QRect(0, 0, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.myTablesButton.setFont(font)
        self.myTablesButton.setObjectName("myTablesButton")

# Выход
        self.EscapeButton = QtWidgets.QPushButton(self.centralwidget5)
        self.EscapeButton.setGeometry(QtCore.QRect(130, 0, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.EscapeButton.setFont(font)
        self.EscapeButton.setObjectName("EscapeButton")
        MainWindow5.setCentralWidget(self.centralwidget5)

# 
        self.retranslateUi(MainWindow5)
        self.listWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow5)

# 
        self.card_count = 0
# 

        self.plus_card_Button.clicked.connect(self.add_card)
        self.minus_card_Button.clicked.connect(self.delete_card)

        self.tabs = QtWidgets.QTabWidget()
        # QtWidgets.QMainWindow.setCentralWidget(QtWidgets.QMainWindow, self.tabs)

    def add_tab(self):
        new_tab = Tab()
        self.tabs.addTab(new_tab, f"Лист {self.tabs.count() + 1}")


    def add_card(self):

        card = QtWidgets.QWidget(self.Table)
        card.setGeometry(QtCore.QRect(0, 80 + self.card_count * 166, 371, 168))
        card.setObjectName(f"card_{self.card_count}")
        self.card_count += 1

        card.setStyleSheet("background-color: rgb(0, 255, 255);\n" "border: 2px solid #000000;\n" "padding: 10px;")

        text_edit = QtWidgets.QPlainTextEdit(card)
        text_edit.setGeometry(QtCore.QRect(10, 17, 351, 133))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        text_edit.setFont(font)
        text_edit.setStyleSheet("background-color: rgb(255, 255, 255);")
        text_edit.setPlainText("название карточки")
        
        # card_option = QtWidgets.QPushButton(card)
        # card_option.setGeometry(QtCore.QRect(330, 120, 31, 31))
        # font = QtGui.QFont()
        # font.setPointSize(12)
        # card_option.setFont(font)
        # card_option.setStyleSheet("background-color: rgb(255, 0, 255);")
        # card_option.setObjectName("card_option")
        # card_option = QtWidgets.QPushButton(self.Card)
        # card_option.setGeometry(QtCore.QRect(330, 120, 31, 31))
        # card_option.setFont(font)
        # card_option.setStyleSheet("background-color: rgb(255, 0, 255);")
        # card_option.setObjectName("card_option")
        # card_option.setText("?")

        card.show()

    def delete_card(self):
        if self.card_count > 0:
            card = self.Table.findChild(QtWidgets.QWidget, f"card_{self.card_count - 1}")
            if card:
                card.deleteLater()
                self.card_count -= 1



    def retranslateUi(self, MainWindow5):
        _translate = QtCore.QCoreApplication.translate
        MainWindow5.setWindowTitle(_translate("MainWindow5", "MainWindow"))
        self.minus_list_Button.setText(_translate("MainWindow5", "-"))
        self.plus_list_Button.setText(_translate("MainWindow5", "+"))
        self.plus_card_Button.setText(_translate("MainWindow5", "+"))
        self.minus_card_Button.setText(_translate("MainWindow5", "-"))
        self.card_label1.setText(_translate("MainWindow5", "Добавить карточку"))
        self.card_label2.setText(_translate("MainWindow5", "Удалить карточку"))
        self.plus_table_Button.setText(_translate("MainWindow5", "+"))
        self.minus_table_Button.setText(_translate("MainWindow5", "-"))
        self.labeltable1.setText(_translate("MainWindow5", "Добавить таблицу"))
        self.labeltable2.setText(_translate("MainWindow5", "Удалить таблицу"))
        self.labelblock1.setText(_translate("MainWindow5", "Удалить столбец"))
        self.labelblock2.setText(_translate("MainWindow5", "Добавить столбец"))
        self.listWidget.setTabText(self.listWidget.indexOf(self.list1), _translate("MainWindow5", "Tab 1"))
        self.myTablesButton.setText(_translate("MainWindow5", "Мои таблицы"))
        self.EscapeButton.setText(_translate("MainWindow5", "Выход"))
        # self.card_option.setText(_translate("MainWindow5", "?"))
        
class Tab(QtWidgets.QWidget):
    def __init__(self):
        super(Tab, self).__init__()
        
        self.layout = QtWidgets.QVBoxLayout()

        self.add_card_button = QtWidgets.QPushButton("Добавить карточку", self)
        self.add_card_button.clicked.connect(self.add_card)

        self.remove_card_button = QtWidgets.QPushButton("Удалить карточку", self)
        self.remove_card_button.clicked.connect(self.remove_card)

        self.layout.addWidget(self.add_card_button)
        self.layout.addWidget(self.remove_card_button)

        self.setLayout(self.layout)

    def add_card(self):
        card = QtWidgets.QTextEdit()
        card.setStyleSheet("background-color: cyan;")
        self.layout.addWidget(card)

    def remove_card(self):
        if self.layout.count() > 2:
            card = self.layout.itemAt(self.layout.count() - 1).widget()
            self.layout.removeWidget(card)
            card.deleteLater()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    card = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(card)
    card.show()
    sys.exit(app.exec_())