# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'page4.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1643, 800)
        font = QtGui.QFont()
        font.setPointSize(12)
        MainWindow.setFont(font)
        MainWindow.setMouseTracking(True)
        MainWindow.setTabletTracking(True)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        MainWindow.setAnimated(True)
        self.centralwidget4 = QtWidgets.QWidget(MainWindow)
        self.centralwidget4.setObjectName("centralwidget4")
        self.icon = QtWidgets.QLabel(self.centralwidget4)
        self.icon.setGeometry(QtCore.QRect(0, 0, 181, 141))
        font = QtGui.QFont()
        font.setKerning(True)
        self.icon.setFont(font)
        self.icon.setAutoFillBackground(False)
        self.icon.setStyleSheet("background-color: rgb(0, 255, 255);\n"
"")
        self.icon.setText("")
        self.icon.setPixmap(QtGui.QPixmap("img/catcat.png"))
        self.icon.setObjectName("icon")
        self.blue_block_up = QtWidgets.QLabel(self.centralwidget4)
        self.blue_block_up.setGeometry(QtCore.QRect(-10, 0, 1641, 161))
        self.blue_block_up.setStyleSheet("background-color: #34fafa;\n"
"border: 1px solid #34fafa;\n"
"border-bottom-color: rgb(0, 0, 0);\n"
"border-right-color: rgb(0, 0, 0);")
        self.blue_block_up.setText("")
        self.blue_block_up.setObjectName("blue_block_up")
        self.purpleblock1 = QtWidgets.QLabel(self.centralwidget4)
        self.purpleblock1.setGeometry(QtCore.QRect(1520, 160, 41, 621))
        self.purpleblock1.setStyleSheet("background-color: rgb(237, 0, 237);\n"
"border: 1px solid #000000;")
        self.purpleblock1.setText("")
        self.purpleblock1.setObjectName("purpleblock1")
        self.purpleblock2 = QtWidgets.QLabel(self.centralwidget4)
        self.purpleblock2.setGeometry(QtCore.QRect(1590, 160, 41, 621))
        self.purpleblock2.setStyleSheet("background-color: rgb(237, 0, 237);\n"
"border: 1px solid #000000;")
        self.purpleblock2.setText("")
        self.purpleblock2.setObjectName("purpleblock2")
        self.backButton = QtWidgets.QPushButton(self.centralwidget4)
        self.backButton.setGeometry(QtCore.QRect(120, 420, 311, 101))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.backButton.setFont(font)
        self.backButton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 10px solid #34fafa;\n"
"border-radius:50\n"
"\n"
"")
        self.backButton.setObjectName("backButton")
        self.line1 = QtWidgets.QFrame(self.centralwidget4)
        self.line1.setGeometry(QtCore.QRect(513, 170, 20, 661))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.line1.setFont(font)
        self.line1.setLineWidth(3)
        self.line1.setFrameShape(QtWidgets.QFrame.VLine)
        self.line1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line1.setObjectName("line1")
        self.cat = QtWidgets.QLabel(self.centralwidget4)
        self.cat.setGeometry(QtCore.QRect(730, 170, 591, 601))
        self.cat.setText("")
        self.cat.setPixmap(QtGui.QPixmap("img/coolcat.png"))
        self.cat.setObjectName("cat")
        self.blue_block_up.raise_()
        self.purpleblock1.raise_()
        self.purpleblock2.raise_()
        self.backButton.raise_()
        self.line1.raise_()
        self.icon.raise_()
        self.cat.raise_()
        MainWindow.setCentralWidget(self.centralwidget4)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        
        iconM = QtGui.QIcon()
        iconM.addPixmap(QtGui.QPixmap("img/coolhat.png"),
        QtGui.QIcon.Selected, QtGui.QIcon.On)
        MainWindow.setWindowIcon(iconM)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Шаманские карточки"))
        self.backButton.setText(_translate("MainWindow", "Вернуться назад"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SettingsWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(SettingsWindow)
    SettingsWindow.show()
    sys.exit(app.exec_())