# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'page6.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class UI_account(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1643, 800)
        font = QtGui.QFont()
        font.setPointSize(12)
        MainWindow.setFont(font)
        MainWindow.setMouseTracking(True)
        MainWindow.setTabletTracking(True)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        MainWindow.setAnimated(True)
        self.centralwidget6 = QtWidgets.QWidget(MainWindow)
        self.centralwidget6.setObjectName("centralwidget6")
        self.icon = QtWidgets.QLabel(self.centralwidget6)
        self.icon.setGeometry(QtCore.QRect(0, 0, 181, 141))
        self.icon.setAutoFillBackground(False)
        self.icon.setStyleSheet("background-color: rgb(0, 255, 255);\n"
"")
        self.icon.setText("")
        self.icon.setPixmap(QtGui.QPixmap("img/catcat.png"))
        self.icon.setObjectName("icon")
        self.sucess_window = QtWidgets.QLabel(self.centralwidget6)
        self.sucess_window.setGeometry(QtCore.QRect(630, 180, 721, 171))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.sucess_window.setFont(font)
        self.sucess_window.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 10px solid #34fafa;\n"
"border-radius:50\n"
"\n"
"\n"
"")
        self.sucess_window.setObjectName("sucess_window")
        self.blue_block_up = QtWidgets.QLabel(self.centralwidget6)
        self.blue_block_up.setGeometry(QtCore.QRect(-10, 0, 1641, 161))
        self.blue_block_up.setStyleSheet("background-color: #34fafa;\n"
"border: 1px solid #34fafa;\n"
"border-bottom-color: rgb(0, 0, 0);\n"
"border-right-color: rgb(0, 0, 0);")
        self.blue_block_up.setText("")
        self.blue_block_up.setObjectName("blue_block_up")
        self.purpleblock1 = QtWidgets.QLabel(self.centralwidget6)
        self.purpleblock1.setGeometry(QtCore.QRect(1520, 160, 41, 621))
        self.purpleblock1.setStyleSheet("background-color: rgb(237, 0, 237);\n"
"border: 1px solid #000000;")
        self.purpleblock1.setText("")
        self.purpleblock1.setObjectName("purpleblock1")
        self.purpleblock2 = QtWidgets.QLabel(self.centralwidget6)
        self.purpleblock2.setGeometry(QtCore.QRect(1590, 160, 41, 621))
        self.purpleblock2.setStyleSheet("background-color: rgb(237, 0, 237);\n"
"border: 1px solid #000000;")
        self.purpleblock2.setText("")
        self.purpleblock2.setObjectName("purpleblock2")
        self.backButton = QtWidgets.QPushButton(self.centralwidget6)
        self.backButton.setGeometry(QtCore.QRect(110, 330, 311, 101))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.backButton.setFont(font)
        self.backButton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 10px solid #34fafa;\n"
"border-radius:50\n"
"\n"
"")
        self.backButton.setObjectName("backButton")
        self.surpriseButton = QtWidgets.QPushButton(self.centralwidget6)
        self.surpriseButton.setGeometry(QtCore.QRect(110, 480, 311, 101))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.surpriseButton.setFont(font)
        self.surpriseButton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 10px solid #34fafa;\n"
"border-radius:50\n"
"\n"
"")
        self.surpriseButton.setObjectName("surpriseButton")
        self.line1 = QtWidgets.QFrame(self.centralwidget6)
        self.line1.setGeometry(QtCore.QRect(513, 170, 20, 661))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.line1.setFont(font)
        self.line1.setLineWidth(3)
        self.line1.setFrameShape(QtWidgets.QFrame.VLine)
        self.line1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line1.setObjectName("line1")
        self.create_tableButton = QtWidgets.QPushButton(self.centralwidget6)
        self.create_tableButton.setGeometry(QtCore.QRect(840, 400, 311, 101))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.create_tableButton.setFont(font)
        self.create_tableButton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 10px solid #34fafa;\n"
"border-radius:50\n"
"\n"
"")
        self.create_tableButton.setObjectName("create_tableButton")
        self.mytableButton = QtWidgets.QPushButton(self.centralwidget6)
        self.mytableButton.setGeometry(QtCore.QRect(840, 540, 311, 101))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.mytableButton.setFont(font)
        self.mytableButton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 10px solid #34fafa;\n"
"border-radius:50\n"
"\n"
"")
        self.mytableButton.setObjectName("mytableButton")
        self.sucess_window.raise_()
        self.blue_block_up.raise_()
        self.purpleblock1.raise_()
        self.purpleblock2.raise_()
        self.backButton.raise_()
        self.surpriseButton.raise_()
        self.line1.raise_()
        self.icon.raise_()
        self.create_tableButton.raise_()
        self.mytableButton.raise_()
        MainWindow.setCentralWidget(self.centralwidget6)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        iconM = QtGui.QIcon()
        iconM.addPixmap(QtGui.QPixmap("img/coolhat.png"),
        QtGui.QIcon.Selected, QtGui.QIcon.On)
        MainWindow.setWindowIcon(iconM)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Шаманские карточки"))
        self.sucess_window.setText(_translate("MainWindow", f"              Добро пожаловать домой, {self.user.login}!"))
        self.backButton.setText(_translate("MainWindow", "Вернуться назад"))
        self.surpriseButton.setText(_translate("MainWindow", "Сюрприз"))
        self.create_tableButton.setText(_translate("MainWindow", "Создать таблицу"))
        self.mytableButton.setText(_translate("MainWindow", "Мои таблицы"))


