# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'page1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon

class UI_mainMenu(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1643, 800)
        MainWindow.setMouseTracking(True)
        MainWindow.setTabletTracking(True)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        
        MainWindow.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.icon = QtWidgets.QLabel(self.centralwidget)
        self.icon.setGeometry(QtCore.QRect(0, 0, 181, 141))
        self.icon.setAutoFillBackground(False)
        self.icon.setStyleSheet("background-color: rgb(0, 255, 255);\n"
"")
        self.icon.setText("")
        self.icon.setPixmap(QtGui.QPixmap("img/catcat.png"))
        self.icon.setObjectName("icon")
        self.welcome_window = QtWidgets.QLabel(self.centralwidget)
        self.welcome_window.setGeometry(QtCore.QRect(680, 260, 721, 171))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.welcome_window.setFont(font)
        self.welcome_window.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 10px solid #34fafa;\n"
"border-radius:50\n"
"\n"
"\n"
"")
        self.welcome_window.setObjectName("welcome_window")
        self.authorizationButton = QtWidgets.QPushButton(self.centralwidget)
        self.authorizationButton.setGeometry(QtCore.QRect(680, 510, 321, 111))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.authorizationButton.setFont(font)
        self.authorizationButton.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.authorizationButton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 10px solid #34fafa;\n"
"border-radius:50\n"
"\n"
"")
        self.authorizationButton.setAutoDefault(False)
        self.authorizationButton.setObjectName("authorizationButton")
        self.registrationButton = QtWidgets.QPushButton(self.centralwidget)
        self.registrationButton.setGeometry(QtCore.QRect(1080, 510, 321, 111))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(20)
        self.registrationButton.setFont(font)
        self.registrationButton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 10px solid #34fafa;\n"
"border-radius:50\n"
"\n"
"")
        self.registrationButton.setObjectName("registrationButton")
        self.story = QtWidgets.QTextBrowser(self.centralwidget)
        self.story.setGeometry(QtCore.QRect(0, 210, 581, 501))
        self.story.setStyleSheet("border: 1px solid #000000;\n"
"background-color: rgb(85, 255, 255);")
        self.story.setObjectName("story")
        self.blue_block_up1 = QtWidgets.QLabel(self.centralwidget)
        self.blue_block_up1.setGeometry(QtCore.QRect(-10, 0, 1641, 161))
        self.blue_block_up1.setStyleSheet("background-color: #34fafa;\n"
"border: 1px solid #34fafa;\n"
"border-bottom-color: rgb(0, 0, 0);\n"
"border-right-color: rgb(0, 0, 0);")
        self.blue_block_up1.setText("")
        self.blue_block_up1.setObjectName("blue_block_up1")
        self.purpleblock1 = QtWidgets.QLabel(self.centralwidget)
        self.purpleblock1.setGeometry(QtCore.QRect(1520, 160, 41, 621))
        self.purpleblock1.setStyleSheet("background-color: rgb(237, 0, 237);\n"
"border: 1px solid #000000;")
        self.purpleblock1.setText("")
        self.purpleblock1.setObjectName("purpleblock1")
        self.purpleblock2 = QtWidgets.QLabel(self.centralwidget)
        self.purpleblock2.setGeometry(QtCore.QRect(1590, 160, 41, 621))
        self.purpleblock2.setStyleSheet("background-color: rgb(237, 0, 237);\n"
"border: 1px solid #000000;")
        self.purpleblock2.setText("")
        self.purpleblock2.setObjectName("purpleblock2")
        self.welcome_window.raise_()
        self.authorizationButton.raise_()
        self.registrationButton.raise_()
        self.story.raise_()
        self.blue_block_up1.raise_()
        self.icon.raise_()
        self.purpleblock1.raise_()
        self.purpleblock2.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        iconM = QtGui.QIcon()
        iconM.addPixmap(QtGui.QPixmap("img/coolhat.png"),
        QtGui.QIcon.Selected, QtGui.QIcon.On)
        MainWindow.setWindowIcon(iconM)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Шаманские карточки"))
        self.welcome_window.setText(_translate("MainWindow", "Добро пожаловать в шаманские карточки!!!"))
        self.authorizationButton.setText(_translate("MainWindow", "Авторизация"))
        self.registrationButton.setText(_translate("MainWindow", "Регистрация"))
        self.story.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt;\">Шаманские таблицы - это событие в мире искусства и технологий.</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:16pt;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Уникальная система списка задач позволяет сыкономить огромное количество времени или  затратить ещё больше на расписания задач.</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Но зато у вас будет красивая табличка, котрую вы можете показать вашей маме и вашим друзьям.</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Технология, завоевавшая критиков и многочисленные награды, теперь доступна только для вас и всем остальным людям на планете.</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Приложение создано 4 творцами, которые хотели изменить мир к лучшему:</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Pybuk</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Dimochka_Chicken_Lover</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">моксим</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Pixel_duck</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p></body></html>"))


