# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mytennistable.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class UI_myTables(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow6")
        MainWindow.resize(1643, 800)
        font = QtGui.QFont()
        font.setPointSize(12)
        MainWindow.setFont(font)
        MainWindow.setMouseTracking(True)
        MainWindow.setTabletTracking(True)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        MainWindow.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.icon = QtWidgets.QLabel(self.centralwidget)
        self.icon.setGeometry(QtCore.QRect(0, 0, 181, 141))
        self.icon.setAutoFillBackground(False)
        self.icon.setStyleSheet("background-color: rgb(0, 255, 255);\n"
"")
        self.icon.setText("")
        self.icon.setPixmap(QtGui.QPixmap("img/catcat.png"))
        self.icon.setObjectName("icon")
        self.blue_block_up = QtWidgets.QLabel(self.centralwidget)
        self.blue_block_up.setGeometry(QtCore.QRect(-60, 0, 1691, 161))
        self.blue_block_up.setStyleSheet("background-color: #34fafa;\n"
"border: 1px solid #34fafa;\n"
"border-bottom-color: rgb(0, 0, 0);\n"
"border-right-color: rgb(0, 0, 0);")
        self.blue_block_up.setText("")
        self.blue_block_up.setObjectName("blue_block_up")
        self.purpleblock1 = QtWidgets.QLabel(self.centralwidget)
        self.purpleblock1.setGeometry(QtCore.QRect(1520, 160, 41, 621))
        self.purpleblock1.setStyleSheet("background-color: rgb(237, 0, 237);\n"
"border: 1px solid #000000;")
        self.purpleblock1.setText("")
        self.purpleblock1.setObjectName("purpleblock1")
        self.purpleblock2 = QtWidgets.QLabel(self.centralwidget)
        self.purpleblock2.setGeometry(QtCore.QRect(1590, 160, 41, 621))
        self.purpleblock2.setStyleSheet("background-color: rgb(237, 0, 237);\n"
"border: 1px solid #000000;")
        self.purpleblock2.setText("")
        self.purpleblock2.setObjectName("purpleblock2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(390, 200, 1121, 571))
        font = QtGui.QFont()
        font.setFamily("News701 BT")
        self.label.setFont(font)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("img/puss in boots.png"))
        self.label.setObjectName("label")
        self.blue_block_up.raise_()
        self.purpleblock1.raise_()
        self.purpleblock2.raise_()
        self.icon.raise_()
        self.label.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.EscapeButton = QtWidgets.QPushButton(self.centralwidget)
        self.EscapeButton.setGeometry(QtCore.QRect(130, 0, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.EscapeButton.setFont(font)
        self.EscapeButton.setObjectName("EscapeButton")
        
        iconM = QtGui.QIcon()
        iconM.addPixmap(QtGui.QPixmap("img/coolhat.png"),
        QtGui.QIcon.Selected, QtGui.QIcon.On)
        MainWindow.setWindowIcon(iconM)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.setWindowIcon(QtGui.QIcon('img/icon.png'))
        
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Шаманские карточки"))
        self.EscapeButton.setText(_translate("MainWindow5", "Выход"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
